import {initializeApp} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import {getDatabase,ref,onValue} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-database.js';
import {firebaseConfig} from './firebase-config.js';
const $=s=>document.querySelector(s);
const names={research:'연구',education:'교육·교재',cases:'코칭사례',ax:'AX·공공혁신',notes:'연구노트',now:'요즘의 관심',columns:'칼럼·기고·인터뷰'};
const descriptions={research:'코칭과 조직, 성장과 변화에 관한 연구를 기록합니다.',education:'강의와 교재, 교육현장의 경험을 소개합니다.',cases:'코칭 현장에서 발견한 가능성과 배움을 나눕니다.',ax:'현장의 문제를 발견하고 디지털 기술로 개선해 가는 과정입니다.',notes:'읽고 쓰고 성찰하며 쌓아 온 생각의 기록입니다.',now:'지금 탐구하고 있는 관심과 질문을 기록합니다.',columns:'칼럼, 기고문, 인터뷰와 외부 매체에 소개된 활동을 기록합니다.'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const vals=o=>Array.isArray(o)?o.filter(Boolean).map((x,i)=>({...x,_key:String(x.id??i)})):Object.entries(o||{}).filter(([,x])=>x&&typeof x==='object').map(([id,x])=>({...x,_key:id}));
const goodUrl=s=>{try{const u=new URL(s);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}};
const kind=x=>{const c=String(x.category||'').trim();if(['교육·교재','강의자료','교육','교재'].includes(c))return'education';if(['코칭사례','사례'].includes(c))return'cases';if(['AX·공공혁신','AX혁신','공공혁신'].includes(c))return'ax';return'notes'};
const param=()=>new URLSearchParams(location.search);
let type='research',all=[],shown=[],data=null;
function syncRoute(){const p=param(),t=p.get('type');type=names[t]?t:'research';$('#pageTitle').textContent=names[type];$('#crumb').textContent=names[type];$('#pageDesc').textContent=descriptions[type];$('#listHeading').textContent=names[type]+' 전체 기록';$('#heroType').textContent=type.toUpperCase()+' COLLECTION';document.title=names[type]+' | JOUNG COACH';document.querySelectorAll('.archiveTabs a').forEach(a=>a.classList.toggle('active',a.dataset.type===type));$('#bottomList').href=`archive.html?type=${type}`;if(data)load(data);}
function load(d){all=type==='research'?vals(d.research):type==='now'?vals(d.nowEntries):type==='columns'?vals(d.columns):vals(d.articles).filter(x=>kind(x)===type);if(type==='now'&&(d.now?.title||d.now?.body))all.push({...d.now,_key:'legacy-now'});all.sort((a,b)=>String(b.date||b.year||'').localeCompare(String(a.date||a.year||'')));render();}
function render(){const q=$('#filter').value.trim().toLocaleLowerCase();shown=all.filter(x=>[x.title,x.summary,x.body,x.meta,x.desc,x.category,x.publisher,x.year,x.date].join(' ').toLocaleLowerCase().includes(q));$('#count').textContent=`총 ${shown.length}개의 기록`;$('#items').innerHTML=shown.map((x,i)=>{const u=goodUrl(x.image);return `<button class="archiveCard" type="button" data-i="${i}">${u?`<img src="${esc(u)}" alt="" loading="lazy">`:''}<span class="archiveCardBody"><small>${esc([x.date||x.year,x.publisher||x.category].filter(Boolean).join(' · '))}</small><strong>${esc(x.title||'제목 없는 기록')}</strong><span class="summary">${esc(x.summary||x.meta||x.desc||'')}</span><span class="read">자세히 읽기 →</span></span></button>`}).join('');$('#empty').hidden=shown.length>0;const id=param().get('item');if(id!==null){const selected=shown.find(x=>x._key===id);if(selected){showDetail(selected,false);return}}$('#articleView').hidden=true;$('#listView').hidden=false;}
function showDetail(x,push=true){if(push){const p=param();p.set('type',type);p.set('item',x._key);history.pushState(null,'','?'+p.toString());}const img=goodUrl(x.image),link=goodUrl(x.link||x.url);$('#detail').innerHTML=`<div class="articleMeta">${esc([x.date||x.year,x.publisher||x.category].filter(Boolean).join(' · '))}</div><h2>${esc(x.title||'제목 없는 기록')}</h2>${x.meta?`<div class="articleKeywords">${esc(x.meta)}</div>`:''}${img?`<img class="articleImage" src="${esc(img)}" alt="관련 이미지">`:''}${x.summary?`<div class="articleSummary">${esc(x.summary)}</div>`:''}<div class="articleBody">${esc(x.body||x.desc||'')}</div>${link?`<div class="articleLink"><a href="${esc(link)}" target="_blank" rel="noopener noreferrer">${type==='columns'?'원문 읽기':'관련 자료 살펴보기'} ↗</a></div>`:''}`;$('#listView').hidden=true;$('#articleView').hidden=false;window.scrollTo({top:0,behavior:'instant'});}
function goBack(){const p=param();p.delete('item');history.pushState(null,'','?'+p.toString());$('#articleView').hidden=true;$('#listView').hidden=false;window.scrollTo({top:0,behavior:'instant'});}
$('#items').addEventListener('click',e=>{const b=e.target.closest('button[data-i]');if(b)showDetail(shown[Number(b.dataset.i)])});$('#filter').addEventListener('input',()=>{const p=param();if(p.has('item')){p.delete('item');history.replaceState(null,'','?'+p.toString())}render()});$('#backToList').addEventListener('click',goBack);window.addEventListener('popstate',syncRoute);syncRoute();
try{const db=getDatabase(initializeApp(firebaseConfig));onValue(ref(db,'homepage'),s=>{data=s.val()||{};load(data);$('#status').textContent=s.exists()?'최신 기록을 표시하고 있습니다.':'등록된 자료가 없습니다.'},e=>{$('#status').textContent='자료를 불러오지 못했습니다: '+e.message;console.error(e)})}catch(e){$('#status').textContent='연결에 문제가 발생했습니다: '+e.message;console.error(e)}
